[package]
name = "whitebase-cerune-native-adapter"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
cerune-lang = {
    git = "https://github.com/Hokutaka/Cerune.git",
    rev = "85be8ab1719cba577acc7c32404bf481ad141769"
}

[target.'cfg(any(all(target_arch = "x86_64", target_os = "windows", target_env = "msvc"), all(target_arch = "x86_64", target_os = "linux", target_env = "gnu")))'.dependencies]
libloading = "0.9"
tempfile = "3"