$ErrorActionPreference = 'Stop'

$rootDirectory = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$outputFile = Join-Path $rootDirectory 'docs\project-tree.md'
$outputRelativePath = 'docs/project-tree.md'

function New-TreeNode {
    param(
        [bool]$IsFile = $false
    )

    return [PSCustomObject]@{
        IsFile   = $IsFile
        Children = @{}
    }
}

function Add-PathToTree {
    param(
        [Parameter(Mandatory)]
        [object]$RootNode,

        [Parameter(Mandatory)]
        [string]$Path
    )

    $parts = @(
        $Path -split '[\\/]' |
            Where-Object {
                -not [string]::IsNullOrWhiteSpace($_)
            }
    )

    $currentNode = $RootNode

    for ($index = 0; $index -lt $parts.Count; $index++) {
        $name = $parts[$index]
        $isFile = $index -eq ($parts.Count - 1)

        if (-not $currentNode.Children.ContainsKey($name)) {
            $currentNode.Children[$name] = New-TreeNode -IsFile $isFile
        }

        $currentNode = $currentNode.Children[$name]
    }
}

function Get-TreeLines {
    param(
        [Parameter(Mandatory)]
        [object]$Node,

        [string]$Prefix = ''
    )

    # PowerShell 5.1によるソースコードの文字化けを避けるため、
    # 罫線文字をUnicodeコードポイントから生成する。
    $branchConnector = (
        [char]0x251C +
        [char]0x2500 +
        [char]0x2500 +
        ' '
    )

    $lastConnector = (
        [char]0x2514 +
        [char]0x2500 +
        [char]0x2500 +
        ' '
    )

    $verticalPrefix = [char]0x2502 + '   '

    $entries = @(
        $Node.Children.GetEnumerator() |
            Sort-Object `
                @{ Expression = { if ($_.Value.IsFile) { 1 } else { 0 } } },
                @{ Expression = { $_.Key } }
    )

    for ($index = 0; $index -lt $entries.Count; $index++) {
        $entry = $entries[$index]
        $isLast = $index -eq ($entries.Count - 1)

        $connector = if ($isLast) {
            $lastConnector
        }
        else {
            $branchConnector
        }

        Write-Output ($Prefix + $connector + $entry.Key)

        if (-not $entry.Value.IsFile) {
            $childPrefix = if ($isLast) {
                $Prefix + '    '
            }
            else {
                $Prefix + $verticalPrefix
            }

            Get-TreeLines `
                -Node $entry.Value `
                -Prefix $childPrefix
        }
    }
}

Push-Location $rootDirectory

try {
    git rev-parse --is-inside-work-tree *> $null

    if ($LASTEXITCODE -ne 0) {
        throw "Git repository was not found: $rootDirectory"
    }

    $files = @(
        git ls-files --cached --others --exclude-standard |
            ForEach-Object {
                $_.Replace('\', '/')
            } |
            Where-Object {
                -not [string]::IsNullOrWhiteSpace($_) -and
                $_ -ne $outputRelativePath
            } |
            Sort-Object -Unique
    )

    if ($LASTEXITCODE -ne 0) {
        throw 'git ls-files failed.'
    }

    $treeRoot = New-TreeNode

    foreach ($file in $files) {
        Add-PathToTree `
            -RootNode $treeRoot `
            -Path $file
    }

    $projectName = Split-Path $rootDirectory -Leaf
    $treeLines = @(Get-TreeLines -Node $treeRoot)

    $outputLines = @(
        '# Project Tree'
        ''
        'This file is generated by `scripts/export-tree.bat`.'
        ''
        '```text'
        $projectName
        $treeLines
        '```'
        ''
    )

    $outputDirectory = Split-Path $outputFile -Parent

        New-Item `
        -ItemType Directory `
        -Path $outputDirectory `
        -Force |
        Out-Null

    [System.IO.File]::WriteAllLines(
        $outputFile,
        [string[]]$outputLines,
        [System.Text.UTF8Encoding]::new($false)
    )

    Write-Host ''
    Write-Host $projectName

    foreach ($line in $treeLines) {
        Write-Host $line
    }

    Write-Host ''
    Write-Host 'Project tree exported:'
    Write-Host $outputFile
}
catch {
    Write-Error $_
    exit 1
}
finally {
    Pop-Location
}