[package]
name = "whitebase-backend-bridge"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
whitebase-backend-contract = { path = "../../whitebase-backend-contract" }
whitebase-rust-backend = {
    path = "../../whitebase-rust-backend"
}
whitebase-cerune-vm-adapter = { path = "../whitebase-cerune-vm-adapter" }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
whitebase-cerune-c-adapter = { path = "../whitebase-cerune-c-adapter" }
whitebase-cerune-llvm-adapter = { path = "../whitebase-cerune-llvm-adapter" }
whitebase-cerune-qbe-adapter = { path = "../whitebase-cerune-qbe-adapter" }
whitebase-cerune-wat-adapter = { path = "../whitebase-cerune-wat-adapter" }
whitebase-cerune-asm-adapter = { path = "../whitebase-cerune-asm-adapter" }

[target.x86_64-pc-windows-msvc.dependencies]
whitebase-cpp-adapter = { path = "../whitebase-cpp-adapter" }
whitebase-asm-adapter = { path = "../whitebase-asm-adapter" }
whitebase-windows-gnu-adapter = { path = "../whitebase-windows-gnu-adapter" }

[target.x86_64-unknown-linux-gnu.dependencies]
whitebase-cpp-adapter = { path = "../whitebase-cpp-adapter" }
whitebase-asm-adapter = { path = "../whitebase-asm-adapter" }
